In [1]:
# Google Colab / local setup
import os, sys, subprocess
from pathlib import Path
if "google.colab" in sys.modules:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=False)
    CODE_ROOT = Path("/content/drive/MyDrive/msc project/code")
    subprocess.check_call([
        sys.executable, "-m", "pip", "install", "-q", "--no-deps", "-e",
        str(CODE_ROOT), 'catboost==1.2.10', 'rapidfuzz==3.14.3',
    ])
else:
    CODE_ROOT = next(
        path for path in (Path.cwd(), *Path.cwd().parents)
        if (path / "pyproject.toml").exists()
    )
os.chdir(CODE_ROOT)
sys.path.insert(0, str(CODE_ROOT))
CODE = CODE_ROOT

# 02e — All-model sentiment policy calibration

## Methodology overview

This notebook continues Notebook 02d and uses the same nine model families, four arms (**No sentiment**, **DeBERTa**, **LLM-matched** and **LLM-full**), DZ55/DZ65/DZ75, 180-day history, fixed 15-minute horizon and 5 bps per side. It does not repeat the 2024 blocking-fold or raw-sentiment experiment.

All three sentiment arms see the same sources; they differ only in the scorer and in how each weights what it reads. **DeBERTa against LLM-full** is the layer-versus-layer comparison, and **LLM-matched against LLM-full** isolates how much of any difference is the scalar rather than the structure.

For each January–June 2025 month, each Model/Arm/DZ is fitted only on the preceding 180 days and predicts that month. The six causal prediction blocks evaluate 33 pre-declared policies: 11 confidence thresholds crossed with TP/SL 150/75, 150/100 and 200/100 bps; hold is one M15 bar. Selection ranks economically adequate policies (at least 50 trades, 15 long, 15 short and four positive months) by Sortino, then Sharpe and net return.

The selected policy is frozen and applied to the exact Notebook 02d July-2025 fit and July-2025–March-2026 predictions. One-minute candles are used only to resolve TP/SL execution after the M15 signal. The forward span cannot change the policy, and Q2-2026 is evaluated separately in Notebook 07.

### 1. Load and validate artifacts
The checks require every Model/Arm root and one unique policy and forward row per Model/Arm/DZ.

In [2]:
from pathlib import Path
import sys
import pandas as pd
from IPython.display import display

pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', None)

CODE_ROOT = Path.cwd().resolve()
if CODE_ROOT.name == 'notebooks':
    CODE_ROOT = CODE_ROOT.parent
if str(CODE_ROOT) not in sys.path:
    sys.path.insert(0, str(CODE_ROOT))

from experiments.all_model_sentiment_policy import ARMS, DEFAULT_ROOT, WIDTHS, validate_policy_model_artifacts
from experiments.all_model_sentiment_policy_scoreboard import build_scoreboards
from experiments.all_model_sentiment_scoreboard import build_scoreboards as build_raw_scoreboards
from experiments.raw_hold_control import MODEL_LABELS, MODEL_NAMES

ROOT = DEFAULT_ROOT
for arm in ARMS:
    for model_name in MODEL_NAMES:
        validate_policy_model_artifacts(ROOT / arm / model_name, model_name=model_name)

tables = build_scoreboards(ROOT)
policies = tables['policies']
economics = tables['economics']
raw_economics = build_raw_scoreboards()['economics']
keys = ['sentiment_arm', 'model_name', 'width_bps']
expected = len(ARMS) * 9 * len(WIDTHS)
assert len(policies) == expected and policies[keys].drop_duplicates().shape[0] == expected
assert len(economics) == expected and economics[keys].drop_duplicates().shape[0] == expected
assert len(raw_economics) == expected and raw_economics[keys].drop_duplicates().shape[0] == expected
assert set(policies['width_bps']) == set(WIDTHS)

### 2. H1 2025 policy selection
Each row is the policy selected from six causal monthly prediction blocks; these are calibration results, not forward results.

In [3]:
from IPython.display import Markdown
h1 = policies[[
    'model_name', 'Arm', 'width_bps', 'tau', 'tp_bps', 'sl_bps',
    'hold_minutes', 'trades', 'pooled_net', 'pooled_sortino',
    'pooled_sharpe', 'positive_segments',
]].copy()
h1['model_name'] = h1['model_name'].map(MODEL_LABELS)
h1.columns = [
    'Model', 'Sentiment', 'DZ', 'Threshold', 'TP', 'SL', 'Hold (min)',
    'Trades', 'Net return', 'Sortino', 'Sharpe', 'Positive months',
]
h1 = h1.sort_values(
    ['Sortino', 'Sharpe', 'Net return'], ascending=False, ignore_index=True
)
display(Markdown('Method: Each Model/Arm/DZ policy is selected on six causal H1 monthly prediction blocks.'))
display(h1.round(3))
display(Markdown('H1 results are calibration evidence, not an independent profitability test.'))

Method: Each Model/Arm/DZ policy is selected on six causal H1 monthly prediction blocks.

,Model,Sentiment,DZ,Threshold,TP,SL,Hold (min),Trades,Net return,Sortino,Sharpe,Positive months
0,MLP,DeBERTa,55,0.80,200,100,15,66,0.065,3.314,1.646,4
1,Logistic Regression,LLM-matched,65,0.80,150,75,15,52,0.046,2.436,1.367,4
2,MLP,LLM-matched,55,0.80,200,100,15,58,0.043,2.316,1.237,3
3,Linear SVM,LLM-matched,65,0.00,150,75,15,19,0.027,1.793,0.974,2
4,Logistic Regression,LLM-full,65,0.80,150,75,15,66,0.028,1.163,0.709,4
5,LSTM,No sentiment,55,0.75,200,100,15,79,0.026,1.150,0.659,4
6,Linear SVM,DeBERTa,75,0.00,150,100,15,12,0.008,0.470,0.297,2
7,LSTM,No sentiment,65,0.75,200,100,15,136,0.007,0.253,0.158,4
8,Linear SVM,No sentiment,75,0.00,200,100,15,17,0.004,0.233,0.142,2
9,Linear SVM,LLM-full,55,0.00,150,75,15,30,0.002,0.115,0.075,1
10,CatBoost,DeBERTa,65,0.70,200,100,15,76,0.003,0.096,0.063,2
11,Linear SVM,DeBERTa,65,0.00,150,75,15,18,0.001,0.075,0.046,1
12,Linear SVM,No sentiment,65,0.00,150,75,15,26,0.001,0.056,0.036,2
13,Logistic Regression,DeBERTa,75,0.80,200,100,15,82,-0.002,-0.082,-0.054,4
14,CatBoost,LLM-full,75,0.65,200,100,15,55,-0.002,-0.091,-0.057,4
15,CatBoost,No sentiment,75,0.70,200,100,15,71,-0.003,-0.098,-0.067,2
16,Logistic Regression,DeBERTa,65,0.75,150,75,15,94,-0.005,-0.184,-0.118,3
17,LSTM,LLM-matched,65,0.80,150,75,15,65,-0.004,-0.227,-0.141,2
18,Linear SVM,LLM-full,75,0.00,200,100,15,12,-0.008,-0.445,-0.288,2
19,XGBoost,No sentiment,65,0.80,150,75,15,103,-0.014,-0.453,-0.301,3
20,Linear SVM,LLM-matched,55,0.00,150,75,15,34,-0.011,-0.488,-0.327,2
21,Logistic Regression,LLM-full,75,0.80,200,100,15,147,-0.018,-0.489,-0.324,2
22,Random Forest,LLM-full,75,0.55,200,100,15,169,-0.018,-0.492,-0.312,2
23,CatBoost,LLM-full,65,0.70,200,100,15,70,-0.021,-0.802,-0.552,2
24,Logistic Regression,LLM-full,55,0.75,200,100,15,50,-0.018,-0.874,-0.535,3
25,LSTM,DeBERTa,65,0.80,150,75,15,78,-0.021,-0.901,-0.607,3
26,XGBoost,No sentiment,75,0.80,150,100,15,93,-0.031,-1.013,-0.723,3
27,Linear SVM,DeBERTa,55,0.00,150,75,15,34,-0.025,-1.088,-0.749,1
28,Linear SVM,LLM-matched,75,0.00,150,75,15,12,-0.018,-1.157,-0.788,2
29,XGBoost,DeBERTa,75,0.75,150,75,15,87,-0.039,-1.297,-0.880,2
30,Random Forest,DeBERTa,75,0.55,200,100,15,192,-0.057,-1.390,-0.927,2
31,XGBoost,LLM-matched,75,0.75,200,100,15,127,-0.064,-1.610,-1.147,3
32,MLP,LLM-matched,65,0.80,200,100,15,162,-0.050,-1.637,-1.080,2
33,Random Forest,LLM-matched,55,0.55,150,75,15,136,-0.054,-1.638,-1.120,2
34,LSTM,LLM-matched,55,0.75,200,100,15,120,-0.048,-1.676,-1.150,2
35,Linear SVM,LLM-full,65,0.00,150,75,15,17,-0.031,-1.714,-1.215,1
36,Random Forest,DeBERTa,65,0.55,150,75,15,159,-0.063,-1.737,-1.196,2
37,XGBoost,DeBERTa,65,0.60,200,100,15,361,-0.089,-1.771,-1.185,2
38,Linear SVM,No sentiment,55,0.00,150,100,15,42,-0.052,-1.794,-1.351,1
39,Logistic Regression,DeBERTa,55,0.70,200,100,15,96,-0.057,-1.800,-1.216,3
40,LSTM,DeBERTa,55,0.70,200,100,15,220,-0.077,-1.903,-1.310,3
41,LSTM,LLM-matched,75,0.80,200,100,15,150,-0.061,-1.909,-1.227,1
42,CatBoost,LLM-matched,75,0.65,200,100,15,82,-0.059,-1.943,-1.427,2
43,CatBoost,LLM-full,55,0.65,200,100,15,165,-0.074,-1.979,-1.379,2
44,Logistic Regression,LLM-matched,75,0.75,200,100,15,188,-0.083,-2.036,-1.360,1
45,Logistic Regression,LLM-matched,55,0.70,200,100,15,101,-0.068,-2.182,-1.481,3
46,MLP,DeBERTa,65,0.80,200,100,15,153,-0.064,-2.193,-1.438,2
47,CatBoost,DeBERTa,75,0.65,150,75,15,64,-0.052,-2.256,-1.681,2
48,MLP,No sentiment,65,0.75,200,100,15,151,-0.075,-2.326,-1.550,2
49,Random Forest,LLM-full,65,0.55,150,75,15,127,-0.083,-2.426,-1.673,2
50,XGBoost,LLM-matched,55,0.75,200,100,15,139,-0.098,-2.466,-1.809,3
51,XGBoost,LLM-full,75,0.70,200,100,15,126,-0.089,-2.477,-1.832,3
52,CatBoost,DeBERTa,55,0.70,200,100,15,84,-0.086,-2.783,-2.071,1
53,CatBoost,LLM-matched,55,0.65,200,100,15,190,-0.122,-2.888,-2.118,2
54,Logistic Regression,No sentiment,65,0.70,200,100,15,153,-0.103,-2.891,-1.917,1
55,GRU,LLM-matched,55,0.70,200,100,15,103,-0.086,-2.901,-2.042,1
56,CatBoost,LLM-matched,65,0.55,200,100,15,285,-0.136,-2.935,-2.056,2
57,GRU,LLM-full,55,0.65,200,100,15,246,-0.126,-2.953,-2.021,2
58,GRU,DeBERTa,55,0.70,200,100,15,104,-0.094,-2.982,-2.122,1
59,MLP,LLM-full,65,0.80,200,100,15,196,-0.115,-3.044,-2.054,1
60,Random Forest,No sentiment,55,0.55,150,75,15,176,-0.111,-3.089,-2.253,0
61,GRU,No sentiment,65,0.75,150,75,15,72,-0.074,-3.096,-2.315,1
62,LSTM,DeBERTa,75,0.75,200,100,15,259,-0.135,-3.127,-2.098,0
63,Random Forest,LLM-matched,75,0.55,200,100,15,194,-0.141,-3.243,-2.342,1
64,MLP,LLM-full,55,0.75,200,100,15,210,-0.129,-3.300,-2.338,0
65,GRU,No sentiment,55,0.65,200,100,15,217,-0.126,-3.311,-2.402,3
66,XGBoost,No sentiment,55,0.80,200,100,15,95,-0.109,-3.357,-2.678,2
67,Random Forest,DeBERTa,55,0.55,150,75,15,123,-0.104,-3.376,-2.418,1
68,LSTM,LLM-full,55,0.75,200,100,15,129,-0.106,-3.386,-2.528,1
69,LSTM,LLM-full,65,0.70,200,100,15,328,-0.165,-3.399,-2.353,1
70,MLP,No sentiment,55,0.70,200,100,15,197,-0.116,-3.423,-2.471,2
71,XGBoost,LLM-full,65,0.80,200,100,15,83,-0.116,-3.452,-2.636,1
72,Random Forest,LLM-matched,65,0.55,200,100,15,165,-0.143,-3.511,-2.510,1
73,XGBoost,DeBERTa,55,0.70,150,100,15,192,-0.141,-3.528,-2.714,4
74,CatBoost,No sentiment,55,0.75,150,100,15,77,-0.094,-3.540,-2.730,1
75,XGBoost,LLM-matched,65,0.65,200,100,15,294,-0.185,-3.610,-2.602,0
76,Random Forest,No sentiment,65,0.55,200,100,15,197,-0.154,-3.691,-2.637,0
77,Logistic Regression,No sentiment,75,0.75,200,100,15,146,-0.131,-3.810,-2.818,2
78,GRU,LLM-matched,75,0.75,200,100,15,192,-0.146,-3.868,-2.777,0
79,Logistic Regression,No sentiment,55,0.65,150,75,15,179,-0.144,-3.942,-2.883,1
80,GRU,DeBERTa,75,0.75,200,100,15,183,-0.149,-3.945,-2.748,0
81,GRU,LLM-matched,65,0.70,150,75,15,229,-0.158,-4.018,-2.991,2
82,GRU,LLM-full,65,0.70,150,75,15,245,-0.183,-4.415,-3.122,1
83,GRU,LLM-full,75,0.75,200,100,15,212,-0.206,-4.525,-3.292,1
84,MLP,LLM-full,75,0.80,200,100,15,281,-0.210,-4.558,-3.229,1
85,CatBoost,No sentiment,65,0.70,150,100,15,106,-0.150,-4.634,-3.658,2
86,Random Forest,LLM-full,55,0.50,200,100,15,364,-0.263,-4.655,-3.308,0
87,GRU,No sentiment,75,0.75,200,100,15,148,-0.163,-4.749,-3.437,0
88,MLP,DeBERTa,75,0.80,200,100,15,268,-0.212,-4.816,-3.370,1
89,GRU,DeBERTa,65,0.65,200,100,15,371,-0.251,-4.915,-3.578,1
90,XGBoost,LLM-full,55,0.75,200,100,15,150,-0.227,-5.247,-4.071,1
91,MLP,LLM-matched,75,0.80,200,100,15,297,-0.252,-5.486,-4.012,1
92,Random Forest,No sentiment,75,0.55,200,100,15,257,-0.278,-5.764,-4.419,0
93,MLP,No sentiment,75,0.80,200,100,15,165,-0.241,-6.214,-4.789,0
94,LSTM,LLM-full,75,0.75,200,100,15,357,-0.338,-6.329,-4.758,2
95,LSTM,No sentiment,75,0.70,200,100,15,359,-0.316,-6.523,-4.875,1
96,Decision Tree,No sentiment,65,0.80,150,100,15,330,-0.220,-6.594,-4.807,0
97,Decision Tree,DeBERTa,65,0.80,150,100,15,321,-0.232,-7.109,-5.137,0
98,Decision Tree,DeBERTa,55,0.75,200,100,15,310,-0.288,-7.259,-5.728,0
99,Decision Tree,DeBERTa,75,0.80,200,100,15,480,-0.405,-7.768,-5.764,0
100,Decision Tree,LLM-matched,65,0.80,200,100,15,329,-0.266,-7.768,-5.718,0
101,Decision Tree,LLM-matched,55,0.75,200,100,15,236,-0.266,-8.477,-7.317,0
102,Decision Tree,LLM-full,65,0.80,150,100,15,297,-0.280,-8.553,-6.377,0
103,Decision Tree,LLM-full,75,0.80,200,100,15,572,-0.479,-8.585,-6.446,1
104,Decision Tree,No sentiment,75,0.80,200,100,15,607,-0.468,-8.890,-6.449,0
105,Decision Tree,LLM-full,55,0.75,200,100,15,364,-0.344,-8.988,-7.392,0
106,Decision Tree,LLM-matched,75,0.80,200,100,15,491,-0.521,-10.412,-7.864,0
107,Decision Tree,No sentiment,55,0.75,200,100,15,362,-0.441,-10.606,-9.207,0

H1 results are calibration evidence, not an independent profitability test.

### 3. Frozen-forward economics
The H1-selected threshold and TP/SL are replayed unchanged on July 2025–March 2026; no row is removed because the final research decision is manual.

In [4]:
from IPython.display import Markdown
forward = economics[[
    'model_name', 'Arm', 'width_bps', 'tau', 'tp_bps', 'sl_bps',
    'max_hold', 'trades', 'net_return', 'sortino', 'sharpe', 'positive_months',
]].copy()
forward['model_name'] = forward['model_name'].map(MODEL_LABELS)
forward['max_hold'] = forward['max_hold'] * 15
forward.columns = [
    'Model', 'Sentiment', 'DZ', 'Threshold', 'TP', 'SL', 'Hold (min)',
    'Trades', 'Net return', 'Sortino', 'Sharpe', 'Positive months',
]
forward = forward.sort_values(['Sortino', 'Sharpe', 'Net return'], ascending=False).reset_index(drop=True)
display(Markdown('Method: H1-selected thresholds and barriers remain unchanged throughout the nine-month forward period.'))
display(forward.round(3))
display(Markdown('Policy calibration creates selective winners but does not make sentiment consistently beneficial.'))

Method: H1-selected thresholds and barriers remain unchanged throughout the nine-month forward period.

,Model,Sentiment,DZ,Threshold,TP,SL,Hold (min),Trades,Net return,Sortino,Sharpe,Positive months
0,Linear SVM,No sentiment,75,0.00,200,100,15,30,0.055,2.409,1.304,6
1,LSTM,No sentiment,55,0.75,200,100,15,54,0.036,1.568,0.859,5
2,Linear SVM,No sentiment,65,0.00,150,75,15,51,0.001,0.035,0.024,4
3,Linear SVM,LLM-full,55,0.00,150,75,15,58,-0.013,-0.412,-0.277,4
4,Linear SVM,LLM-full,75,0.00,200,100,15,19,-0.010,-0.422,-0.279,2
5,Linear SVM,LLM-full,65,0.00,150,75,15,30,-0.018,-0.752,-0.525,1
6,Linear SVM,LLM-matched,55,0.00,150,75,15,92,-0.040,-0.999,-0.699,3
7,XGBoost,No sentiment,65,0.80,150,75,15,131,-0.054,-1.368,-0.923,4
8,CatBoost,DeBERTa,65,0.70,200,100,15,38,-0.039,-1.400,-1.067,4
9,Linear SVM,No sentiment,55,0.00,150,100,15,80,-0.070,-1.650,-1.202,3
10,Linear SVM,LLM-matched,75,0.00,150,75,15,39,-0.057,-1.810,-1.351,3
11,GRU,No sentiment,65,0.75,150,75,15,96,-0.053,-1.924,-1.400,2
12,CatBoost,No sentiment,75,0.70,200,100,15,92,-0.080,-2.098,-1.474,4
13,CatBoost,DeBERTa,55,0.70,200,100,15,127,-0.101,-2.209,-1.619,2
14,CatBoost,LLM-full,65,0.70,200,100,15,114,-0.098,-2.371,-1.752,2
15,LSTM,No sentiment,65,0.75,200,100,15,240,-0.114,-2.391,-1.622,2
16,CatBoost,LLM-matched,75,0.65,200,100,15,92,-0.076,-2.422,-1.678,4
17,Logistic Regression,LLM-matched,65,0.80,150,75,15,164,-0.105,-2.464,-1.756,2
18,Linear SVM,LLM-matched,65,0.00,150,75,15,71,-0.093,-2.511,-1.972,2
19,MLP,LLM-matched,55,0.80,200,100,15,259,-0.131,-2.643,-1.858,3
20,XGBoost,LLM-full,75,0.70,200,100,15,155,-0.134,-2.800,-2.000,3
21,Logistic Regression,No sentiment,75,0.75,200,100,15,189,-0.149,-2.997,-2.171,2
22,CatBoost,LLM-full,75,0.65,200,100,15,88,-0.124,-3.085,-2.322,4
23,Logistic Regression,LLM-full,65,0.80,150,75,15,167,-0.136,-3.244,-2.394,1
24,XGBoost,No sentiment,55,0.80,200,100,15,130,-0.147,-3.294,-2.430,2
25,LSTM,LLM-matched,65,0.80,150,75,15,262,-0.174,-3.458,-2.485,1
26,GRU,No sentiment,75,0.75,200,100,15,95,-0.128,-3.466,-2.779,1
27,XGBoost,LLM-full,65,0.80,200,100,15,114,-0.170,-3.469,-2.659,3
28,XGBoost,DeBERTa,75,0.75,150,75,15,81,-0.134,-3.511,-2.785,3
29,GRU,LLM-full,75,0.75,200,100,15,163,-0.164,-3.619,-2.700,4
30,Logistic Regression,LLM-full,75,0.80,200,100,15,184,-0.200,-3.695,-2.771,2
31,Logistic Regression,LLM-full,55,0.75,200,100,15,188,-0.193,-3.946,-2.994,1
32,Random Forest,LLM-matched,55,0.55,150,75,15,112,-0.136,-4.043,-3.122,3
33,Logistic Regression,No sentiment,55,0.65,150,75,15,269,-0.232,-4.292,-3.092,0
34,XGBoost,No sentiment,75,0.80,150,100,15,98,-0.174,-4.326,-3.499,1
35,LSTM,LLM-matched,55,0.75,200,100,15,243,-0.245,-4.331,-3.322,2
36,XGBoost,LLM-full,55,0.75,200,100,15,260,-0.266,-4.362,-3.309,1
37,LSTM,LLM-matched,75,0.80,200,100,15,219,-0.236,-4.489,-3.472,2
38,GRU,LLM-matched,75,0.75,200,100,15,161,-0.185,-4.536,-3.544,0
39,CatBoost,DeBERTa,75,0.65,150,75,15,69,-0.151,-4.555,-3.949,1
40,GRU,No sentiment,55,0.65,200,100,15,161,-0.214,-4.714,-3.663,1
41,CatBoost,No sentiment,65,0.70,150,100,15,151,-0.246,-4.736,-3.859,3
42,XGBoost,LLM-matched,75,0.75,200,100,15,125,-0.218,-4.753,-3.760,2
43,Logistic Regression,LLM-matched,75,0.75,200,100,15,306,-0.300,-4.889,-3.687,1
44,Logistic Regression,LLM-matched,55,0.70,200,100,15,275,-0.292,-4.977,-3.763,1
45,XGBoost,DeBERTa,65,0.60,200,100,15,241,-0.309,-5.036,-3.878,3
46,GRU,LLM-matched,55,0.70,200,100,15,174,-0.211,-5.042,-3.889,0
47,XGBoost,LLM-matched,55,0.75,200,100,15,274,-0.327,-5.207,-4.037,1
48,CatBoost,LLM-matched,65,0.55,200,100,15,273,-0.322,-5.289,-3.976,1
49,CatBoost,No sentiment,55,0.75,150,100,15,92,-0.215,-5.330,-4.623,1
50,MLP,No sentiment,55,0.70,200,100,15,229,-0.294,-5.471,-4.274,0
51,XGBoost,LLM-matched,65,0.65,200,100,15,239,-0.338,-5.548,-4.320,2
52,Logistic Regression,No sentiment,65,0.70,200,100,15,303,-0.328,-5.583,-4.323,0
53,CatBoost,LLM-full,55,0.65,200,100,15,245,-0.342,-5.598,-4.607,0
54,GRU,LLM-full,65,0.70,150,75,15,427,-0.369,-5.712,-4.216,1
55,XGBoost,DeBERTa,55,0.70,150,100,15,348,-0.414,-5.848,-4.653,0
56,Random Forest,No sentiment,55,0.55,150,75,15,142,-0.228,-5.858,-4.965,1
57,LSTM,LLM-full,55,0.75,200,100,15,278,-0.378,-5.858,-4.691,3
58,LSTM,DeBERTa,65,0.80,150,75,15,362,-0.318,-5.905,-4.515,2
59,MLP,DeBERTa,55,0.80,200,100,15,372,-0.415,-6.301,-4.882,1
60,CatBoost,LLM-matched,55,0.65,200,100,15,262,-0.407,-6.409,-5.233,1
61,MLP,No sentiment,75,0.80,200,100,15,280,-0.401,-6.453,-5.058,1
62,LSTM,LLM-full,75,0.75,200,100,15,450,-0.478,-6.533,-5.017,0
63,Random Forest,DeBERTa,55,0.55,150,75,15,165,-0.284,-6.572,-5.747,1
64,Random Forest,LLM-full,65,0.55,150,75,15,327,-0.407,-6.597,-5.161,1
65,Random Forest,LLM-matched,65,0.55,200,100,15,295,-0.396,-6.706,-5.364,2
66,GRU,LLM-matched,65,0.70,150,75,15,425,-0.440,-6.906,-5.340,1
67,LSTM,LLM-full,65,0.70,200,100,15,715,-0.559,-6.929,-5.302,2
68,LSTM,No sentiment,75,0.70,200,100,15,472,-0.499,-6.954,-5.245,1
69,Random Forest,LLM-full,75,0.55,200,100,15,360,-0.487,-7.026,-5.521,2
70,Random Forest,DeBERTa,75,0.55,200,100,15,305,-0.456,-7.108,-5.626,2
71,Random Forest,DeBERTa,65,0.55,150,75,15,300,-0.432,-7.125,-5.642,1
72,Random Forest,LLM-matched,75,0.55,200,100,15,334,-0.495,-7.518,-5.865,2
73,Decision Tree,LLM-full,55,0.75,200,100,15,495,-0.448,-7.562,-6.187,0
74,Random Forest,LLM-full,55,0.50,200,100,15,482,-0.586,-7.606,-5.969,1
75,GRU,LLM-full,55,0.65,200,100,15,487,-0.571,-7.729,-6.187,0
76,MLP,No sentiment,65,0.75,200,100,15,398,-0.579,-7.765,-6.211,0
77,MLP,LLM-matched,75,0.80,200,100,15,530,-0.604,-7.907,-6.241,1
78,GRU,DeBERTa,55,0.70,200,100,15,451,-0.473,-8.106,-6.470,0
79,MLP,LLM-full,55,0.75,200,100,15,465,-0.598,-8.289,-6.657,0
80,MLP,DeBERTa,75,0.80,200,100,15,657,-0.675,-8.290,-6.469,0
81,GRU,DeBERTa,75,0.75,200,100,15,374,-0.454,-8.327,-6.752,2
82,MLP,LLM-full,65,0.80,200,100,15,498,-0.598,-8.396,-6.625,0
83,MLP,LLM-full,75,0.80,200,100,15,570,-0.647,-8.509,-6.646,0
84,Random Forest,No sentiment,65,0.55,200,100,15,438,-0.607,-8.703,-6.917,1
85,LSTM,DeBERTa,75,0.75,200,100,15,610,-0.646,-8.893,-7.075,1
86,Random Forest,No sentiment,75,0.55,200,100,15,403,-0.636,-8.935,-7.197,1
87,MLP,LLM-matched,65,0.80,200,100,15,520,-0.676,-8.940,-7.150,0
88,Linear SVM,DeBERTa,55,0.00,150,75,15,658,-0.527,-9.429,-7.154,4
89,Decision Tree,DeBERTa,75,0.80,200,100,15,482,-0.553,-9.682,-7.972,0
90,MLP,DeBERTa,65,0.80,200,100,15,817,-0.863,-10.062,-7.866,0
91,LSTM,DeBERTa,55,0.70,200,100,15,842,-0.936,-10.864,-8.777,0
92,Linear SVM,DeBERTa,75,0.00,150,100,15,565,-0.573,-11.020,-9.379,3
93,Logistic Regression,DeBERTa,75,0.80,200,100,15,721,-0.782,-11.028,-8.917,1
94,Linear SVM,DeBERTa,65,0.00,150,75,15,624,-0.622,-11.589,-9.671,2
95,Decision Tree,DeBERTa,65,0.80,150,100,15,741,-0.926,-12.268,-10.162,0
96,Decision Tree,DeBERTa,55,0.75,200,100,15,810,-0.845,-12.407,-10.355,0
97,Logistic Regression,DeBERTa,65,0.75,150,75,15,1011,-1.002,-12.857,-10.294,0
98,Logistic Regression,DeBERTa,55,0.70,200,100,15,1062,-1.126,-13.053,-10.719,0
99,Decision Tree,LLM-matched,55,0.75,200,100,15,1037,-1.033,-13.084,-10.923,0
100,Decision Tree,No sentiment,55,0.75,200,100,15,1037,-1.033,-13.084,-10.923,0
101,Decision Tree,No sentiment,65,0.80,150,100,15,797,-1.054,-13.374,-11.267,0
102,Decision Tree,No sentiment,75,0.80,200,100,15,790,-0.944,-13.417,-11.476,0
103,Decision Tree,LLM-matched,65,0.80,200,100,15,907,-1.159,-13.857,-11.543,0
104,Decision Tree,LLM-full,65,0.80,150,100,15,1006,-1.230,-14.662,-12.149,0
105,GRU,DeBERTa,65,0.65,200,100,15,1534,-1.512,-15.116,-12.408,1
106,Decision Tree,LLM-matched,75,0.80,200,100,15,1101,-1.218,-15.634,-13.326,0
107,Decision Tree,LLM-full,75,0.80,200,100,15,1223,-1.316,-15.711,-13.230,0

Policy calibration creates selective winners but does not make sentiment consistently beneficial.

### 4. Five uncalibrated model-family leaders
This is the policy-free Notebook 02d control: each family keeps its best Sentiment/DZ row by raw-forward Sortino, then Sharpe and net return.

In [5]:
from IPython.display import Markdown
raw_leaders = raw_economics.sort_values(
    ['sortino', 'sharpe', 'net_return'], ascending=False
).drop_duplicates('model_name').head(5).copy()
raw_leaders['model_name'] = raw_leaders['model_name'].map(MODEL_LABELS)
raw_leaders = raw_leaders[[
    'model_name', 'Arm', 'width_bps', 'hold_minutes', 'trades',
    'net_return', 'sortino', 'sharpe', 'positive_months',
]]
raw_leaders.columns = [
    'Model', 'Sentiment', 'DZ', 'Hold (min)', 'Trades', 'Net return',
    'Sortino', 'Sharpe', 'Positive months',
]
display(Markdown('Method: The five raw controls retain one best Arm/DZ row per family before policy calibration.'))
display(raw_leaders.round(3))
display(Markdown('These rows provide the policy-free reference for the calibrated comparison.'))

Method: The five raw controls retain one best Arm/DZ row per family before policy calibration.

,Model,Sentiment,DZ,Hold (min),Trades,Net return,Sortino,Sharpe,Positive months
103,Linear SVM,No sentiment,75,15,40,0.075,1.838,1.201,6
104,XGBoost,DeBERTa,75,15,585,-0.620,-5.964,-4.736,1
72,CatBoost,DeBERTa,75,15,273,-0.479,-6.091,-5.014,1
96,Random Forest,DeBERTa,75,15,2437,-2.724,-16.599,-13.210,0
87,Logistic Regression,No sentiment,75,15,4479,-4.473,-22.733,-18.388,0

These rows provide the policy-free reference for the calibrated comparison.

### 5. Five calibrated model-family leaders
Each family keeps its best Arm/DZ/policy row; the table then reports the top five families by forward Sortino, with Sharpe and net return as tie-breakers. Because a family shortlist can only show one row per model, the per-arm leaders are reported separately below — otherwise an arm whose best row shares a family with another arm's would be invisible.

In [6]:
from IPython.display import Markdown
leaders = economics.sort_values(
    ['sortino', 'sharpe', 'net_return'], ascending=False
).drop_duplicates('model_name').head(5).copy()
leaders['model_name'] = leaders['model_name'].map(MODEL_LABELS)
leaders['max_hold'] = leaders['max_hold'] * 15
leaders = leaders[[
    'model_name', 'Arm', 'width_bps', 'tau', 'tp_bps', 'sl_bps',
    'max_hold', 'trades', 'net_return', 'sortino', 'sharpe', 'positive_months',
]]
leaders.columns = [
    'Model', 'Sentiment', 'DZ', 'Threshold', 'TP', 'SL', 'Hold (min)',
    'Trades', 'Net return', 'Sortino', 'Sharpe', 'Positive months',
]
display(Markdown('Method: One calibrated row per family is ranked descriptively on forward Sortino, Sharpe and Net.'))
display(leaders.round(3))
display(Markdown('These leaders are development candidates, not Q2-selected winners.'))

per_arm = economics.sort_values(
    ['sortino', 'sharpe', 'net_return'], ascending=False
).drop_duplicates('sentiment_arm').copy()
per_arm['model_name'] = per_arm['model_name'].map(MODEL_LABELS)
per_arm['max_hold'] = per_arm['max_hold'] * 15
per_arm['gross_bps'] = per_arm['gross_return'] / per_arm['trades'].clip(lower=1) * 1e4
per_arm = per_arm[[
    'Arm', 'model_name', 'width_bps', 'tau', 'tp_bps', 'sl_bps', 'max_hold',
    'trades', 'net_return', 'sortino', 'sharpe', 'positive_months', 'gross_bps',
]]
per_arm.columns = [
    'Arm', 'Model', 'DZ', 'Threshold', 'TP', 'SL', 'Hold (min)', 'Trades',
    'Net return', 'Sortino', 'Sharpe', 'Positive months', 'Gross bps/trade',
]
display(Markdown('Method: Each sentiment arm retains its strongest calibrated row under the same ranking rule.'))
display(per_arm.round(3).reset_index(drop=True))
display(Markdown('Best-row results do not show consistent paired improvement across families.'))

paired = economics.pivot_table(
    index=['model_name', 'width_bps'], columns='sentiment_arm', values='net_return')
cells = len(paired)
for arm, label in (('classic', 'DeBERTa'), ('llm', 'LLM-matched'), ('llm_full', 'LLM-full')):
    if arm not in paired:
        continue
    delta = paired[arm] - paired['none']
if {'llm_full', 'classic'} <= set(paired.columns):
    delta = paired['llm_full'] - paired['classic']

raw_by_model = raw_economics.sort_values(
    ['sortino', 'sharpe', 'net_return'], ascending=False
).drop_duplicates('model_name').set_index('model_name')
calibrated_by_model = economics.sort_values(
    ['sortino', 'sharpe', 'net_return'], ascending=False
).drop_duplicates('model_name').set_index('model_name')
improvement = calibrated_by_model[['sortino', 'net_return']].join(
    raw_by_model[['sortino', 'net_return']],
    how='inner',
    lsuffix='_calibrated',
    rsuffix='_raw',
)
assert len(improvement) == 9
sortino_improvements = int(
    (improvement['sortino_calibrated'] > improvement['sortino_raw']).sum()
)
net_improvements = int(
    (improvement['net_return_calibrated'] > improvement['net_return_raw']).sum()
)

Method: One calibrated row per family is ranked descriptively on forward Sortino, Sharpe and Net.

,Model,Sentiment,DZ,Threshold,TP,SL,Hold (min),Trades,Net return,Sortino,Sharpe,Positive months
103,Linear SVM,No sentiment,75,0.00,200,100,15,30,0.055,2.409,1.304,6
19,LSTM,No sentiment,55,0.75,200,100,15,54,0.036,1.568,0.859,5
71,XGBoost,No sentiment,65,0.80,150,75,15,131,-0.054,-1.368,-0.923,4
36,CatBoost,DeBERTa,65,0.70,200,100,15,38,-0.039,-1.400,-1.067,4
47,GRU,No sentiment,65,0.75,150,75,15,96,-0.053,-1.924,-1.400,2

These leaders are development candidates, not Q2-selected winners.

Method: Each sentiment arm retains its strongest calibrated row under the same ranking rule.

,Arm,Model,DZ,Threshold,TP,SL,Hold (min),Trades,Net return,Sortino,Sharpe,Positive months,Gross bps/trade
0,No sentiment,Linear SVM,75,0.0,200,100,15,30,0.055,2.409,1.304,6,28.182
1,LLM-full,Linear SVM,55,0.0,150,75,15,58,-0.013,-0.412,-0.277,4,7.750
2,LLM-matched,Linear SVM,55,0.0,150,75,15,92,-0.040,-0.999,-0.699,3,5.673
3,DeBERTa,CatBoost,65,0.7,200,100,15,38,-0.039,-1.400,-1.067,4,-0.215

Best-row results do not show consistent paired improvement across families.

### 6. Handoff
The five rows above are forward-development candidates, not final lockbox winners. They may proceed to ensemble testing, while Q2-2026 is evaluated separately in Notebook 07 until the final specification is frozen.